import { useState } from 'react';

const finca=()=>({ubicacion:'',finca:'',superficie:'',tenencia:'',valor:'',gravamen:''});
const bien=()=>({tipo:'',marca:'',anio:'',valor:'',deuda:''});
const ganado=()=>({especie:'',cantidad:'',unitario:'',total:'',gravamen:''});
const cultivos=['SOJA','MAIZ','TRIGO','CHIA','GIRASOL','SESAMO','MANI','CAÑA','PASTURA'];
const referencias=['BANCO 1','BANCO 2','PROV. 1','PROV. 2','PROV. 3'];

function Field({label,value,onChange,type='text'}){return <label className="field"><span>{label}</span><input type={type} value={value||''} onChange={e=>onChange(e.target.value)}/></label>}
function Checks({items,value,onChange}){return <div className="checks">{items.map(x=><label className="check" key={x}><input type="checkbox" checked={value.includes(x)} onChange={()=>onChange(value.includes(x)?value.filter(v=>v!==x):[...value,x])}/>{x}</label>)}</div>}
function Section({n,title,children}){return <section><h2>{n}. {title}</h2>{children}</section>}
function Table({heads,children}){return <div className="table-wrap"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}

export default function App(){
 const [d,setD]=useState({fecha:new Date().toISOString().slice(0,10),tipo:'Persona Física',nombre:'',ci:'',telefono:'',domicilio:'',email:'',actividad:[],fincas:[finca()],reventa:[],servicios:[],prod:cultivos.map(c=>({cultivo:c,ant:'',rnd:'',actual:'',tn:''})),siembra:'',inicio:'',fin:'',bienes:[bien()],ganado:[ganado()],refs:referencias.map(tipo=>({tipo,entidad:'',contacto:'',telefono:''})),titular:'',ruc:'',aclaracion:''});
 const set=(k,v)=>setD(x=>({...x,[k]:v}));
 const row=(k,i,f,v)=>set(k,d[k].map((r,n)=>n===i?{...r,[f]:v}:r));
 const add=(k,make)=>set(k,[...d[k],make()]);
 const del=(k,i)=>set(k,d[k].filter((_,n)=>n!==i));
 return <><div className="toolbar no-print"><div><b>IBC MAS FERTIL</b><small>Relevamiento Técnico Integral y Multisectorial</small></div><button onClick={()=>window.print()}>GENERAR PDF / IMPRIMIR</button></div>
 <main className="paper"><header><div className="logo">más<span>fertil</span><small>FERTILIZANTES</small></div><div className="granu">GRANU+</div></header><h1>(IBC) TÉCNICO INTEGRAL Y MULTISECTORIAL</h1>
 <Field label="FECHA" value={d.fecha} onChange={v=>set('fecha',v)} type="date"/>
 <Section n="1" title="DATOS DEL CLIENTE"><div className="checks"><label className="check"><input type="radio" checked={d.tipo==='Persona Física'} onChange={()=>set('tipo','Persona Física')}/> Persona Física</label><label className="check"><input type="radio" checked={d.tipo==='Persona Jurídica'} onChange={()=>set('tipo','Persona Jurídica')}/> Persona Jurídica</label></div><div className="grid two"><Field label="NOMBRE / RAZÓN SOCIAL" value={d.nombre} onChange={v=>set('nombre',v)}/><Field label="C.I. / RUC" value={d.ci} onChange={v=>set('ci',v)}/><Field label="TELÉFONO" value={d.telefono} onChange={v=>set('telefono',v)}/><Field label="DOMICILIO / CIUDAD" value={d.domicilio} onChange={v=>set('domicilio',v)}/><Field label="E-MAIL" value={d.email} onChange={v=>set('email',v)}/></div></Section>
 <Section n="2" title="PERFIL DE ACTIVIDAD Y SUPERFICIE"><Checks items={['Agrícola','Ganadera','Comercial/Revendedor','Servicios']} value={d.actividad} onChange={v=>set('actividad',v)}/><Table heads={['Ubicación GPS/Localidad','Finca / Padrón / Cta. Cte./Lote/Manzana','Superficie ha.','Tenencia','Valor estimado Gs/Usd','Hipoteca / Gravamen']}>{d.fincas.map((r,i)=><tr key={i}>{Object.keys(r).map(f=><td key={f}><input value={r[f]} onChange={e=>row('fincas',i,f,e.target.value)}/></td>)}</tr>)}</Table><button className="link no-print" onClick={()=>add('fincas',finca)}>+ Agregar ubicación</button></Section>
 <Section n="2.1" title="MÓDULO COMERCIAL Y DE SERVICIOS"><b>REVENTA</b><Checks items={['Agroquímicos','Fertilizantes','Semillas']} value={d.reventa} onChange={v=>set('reventa',v)}/><b>SERVICIOS</b><Checks items={['Consultoría','Maquinaria Pesada','Logística','Asistencia Técnica','Acopio Silo']} value={d.servicios} onChange={v=>set('servicios',v)}/></Section>
 <Section n="3" title="PLAN DE PRODUCCIÓN"><Table heads={['CULTIVO','Has. ANT.','Rnd. Kg','Has. Actual','TN Estimada']}>{d.prod.map((r,i)=><tr key={r.cultivo}><td><b>{r.cultivo}</b></td>{['ant','rnd','actual','tn'].map(f=><td key={f}><input value={r[f]} onChange={e=>row('prod',i,f,e.target.value)}/></td>)}</tr>)}</Table></Section>
 <div className="page-break"/><Section n="3.1" title="FECHAS PRODUCTIVAS"><div className="grid three"><Field label="Fecha estimada de siembra" value={d.siembra} onChange={v=>set('siembra',v)} type="date"/><Field label="Inicio cosecha" value={d.inicio} onChange={v=>set('inicio',v)} type="date"/><Field label="Fin cosecha" value={d.fin} onChange={v=>set('fin',v)} type="date"/></div></Section>
 <Section n="4" title="MANIFESTACIÓN DE BIENES Y ACTIVOS PRODUCTIVOS"><p className="hint">Completar los principales bienes utilizados o vinculados a la actividad declarada. Indicar valor estimado y existencia de deuda o gravamen.</p><h3>4.1 MAQUINARIAS, EQUIPOS AGRÍCOLAS, VEHÍCULOS Y RODADOS</h3><Table heads={['Tipo / Equipo / Vehículo','Marca / Modelo','Año','Valor mercado Gs/Usd','Deuda / Prenda']} >{d.bienes.map((r,i)=><tr key={i}>{Object.keys(r).map(f=><td key={f}><input value={r[f]} onChange={e=>row('bienes',i,f,e.target.value)}/></td>)}</tr>)}</Table><button className="link no-print" onClick={()=>add('bienes',bien)}>+ Agregar bien</button><h3>4.2 GANADO / SEMOVIENTES</h3><Table heads={['Especie / Categoría','Cantidad','Valor unitario Gs/Usd','Valor total Gs/Usd','Gravamen']} >{d.ganado.map((r,i)=><tr key={i}>{Object.keys(r).map(f=><td key={f}><input value={r[f]} onChange={e=>row('ganado',i,f,e.target.value)}/></td>)}</tr>)}</Table><button className="link no-print" onClick={()=>add('ganado',ganado)}>+ Agregar ganado</button></Section>
 <div className="page-break"/><Section n="5" title="REFERENCIAS"><Table heads={['ENTIDAD','CONTACTO','TELÉFONO']}>{d.refs.map((r,i)=><tr key={r.tipo}><td><b>{r.tipo}:</b></td><td><input placeholder="Entidad / contacto" value={r.entidad+' '+r.contacto} onChange={e=>row('refs',i,'entidad',e.target.value)}/></td><td><input value={r.telefono} onChange={e=>row('refs',i,'telefono',e.target.value)}/></td></tr>)}</Table></Section>
 <Section n="6" title="DECLARACIÓN Y AUTORIZACIÓN"><p>Declaro bajo fe de juramento que la información consignada en el presente formulario es verdadera, completa y corresponde a mi situación patrimonial y productiva a la fecha de su suscripción. Asimismo, me comprometo a informar cualquier modificación relevante de los bienes, obligaciones, garantías o situación productiva declarada.</p><p>En cumplimiento de la Ley N° 6.534/20 "De Protección de Datos Personales Crediticios" y demás disposiciones concordantes, autorizo en forma expresa, libre e irrevocable a MAS FERTIL SAE, conforme al Art. 917 inc. a) del Código Civil Paraguayo, a recabar, verificar y confirmar por sí o a través de terceros habilitados, información sobre mi situación patrimonial, solvencia económica y cumplimiento de obligaciones comerciales, financieras y tributarias, ante registros públicos o empresas de información crediticia privadas, con la finalidad exclusiva de análisis de créditos u operaciones presentes o futuras.</p><div className="grid two"><Field label="TITULAR/REPRESENTANTE LEGAL" value={d.titular} onChange={v=>set('titular',v)}/><Field label="RUC/CI N°" value={d.ruc} onChange={v=>set('ruc',v)}/></div><div className="signature"><div className="line"/><b>TITULAR/REPRESENTANTE LEGAL</b><Field label="ACLARACION" value={d.aclaracion} onChange={v=>set('aclaracion',v)}/><Field label="RUC/CI N°" value={d.ruc} onChange={v=>set('ruc',v)}/></div></Section>
 <footer>FORM. IBCTIM. V6 MFS SETIEMBRE 26</footer></main></>;
}
